version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: oxdium/yamdb:latest
    container_name: 'web'
    restart: always
    depends_on:
      - db
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - web
 
volumes:
  db_volume:
  static_volume:
  media_volume:
