# Generated by Django 3.2 on 2023-01-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                max_length=256, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(
                max_length=256, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(
                db_index=True, max_length=256, verbose_name='Название произведения'),
        ),
    ]
