# Generated by Django 3.2 on 2023-01-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_titlegenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleGenre',
        ),
    ]
