# Generated by Django 3.2 on 2023-01-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_titlegenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleGenre',
        ),
    ]
