# Generated by Django 3.2 on 2023-01-10 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_delete_titlegenre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['pub_date'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка ниже 1, невозможна'), django.core.validators.MaxValueValidator(10, message='Оценка больше 10, невозможна')], verbose_name='Оценка'),
        ),
    ]
